---
apiVersion: v1
kind: Service
metadata:
  name: scaling-history-svc
  namespace: mcm-ca-team
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: scaling-history-app
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: scaling-history-app
  namespace: mcm-ca-team
  labels:
    app.kubernetes.io/name: "scaling-history-app"
    networking.gardener.cloud/to-dns: allowed
    networking.gardener.cloud/to-runtime-apiserver: allowed
    networking.resources.gardener.cloud/to-kube-apiserver-tcp-443: allowed
    role: cluster-autoscaler
    app: kubernetes
    gardener.cloud/role: controlplane
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key:  "app.kubernetes.io/name"
                operator: In
                values:
                  - "scaling-history-recorder"
          topologyKey: "kubernetes.io/hostname"
  terminationGracePeriodSeconds: 30
  serviceAccountName: "default"
  containers:
    - name: app
      image: ${DOCKERHUB_USER}/scaling-history-app:latest
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: 500Mi
        limits:
          memory: 1Gi
      env:
        - name: MODE
          value: in-utility-cluster
        - name: DB_DIR
          value: /data/db
        - name: REPORT_DIR
          value: /data/reports
        - name: DOCKERHUB_USER
          value: ${DOCKERHUB_USER}
      volumeMounts:
        - mountPath: /data
          name: data-dir
        - mountPath: /cfg
          name: recorder-config
  volumes:
    - name: data-dir
      persistentVolumeClaim:
        claimName: scaling-history-data
    - name: recorder-config
      projected:
        sources:
        - configMap:
            name: scaling-history-recorder-config