#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: scaling-history-reports
#  namespace: mcm-ca-team
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 20Gi
#  storageClassName: default

---
apiVersion: v1
kind: Service
metadata:
  name: scaling-history-svc
  namespace: mcm-ca-team
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: scaling-history-app
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: scaling-history-app
  namespace: mcm-ca-team
  labels:
    app.kubernetes.io/name: "scaling-history-app"
    networking.gardener.cloud/to-dns: allowed
    networking.gardener.cloud/to-runtime-apiserver: allowed
    networking.resources.gardener.cloud/to-kube-apiserver-tcp-443: allowed
    role: cluster-autoscaler
    app: kubernetes
    gardener.cloud/role: controlplane
spec:
  tolerations:
    - key: dedicated
      value: scaling-history
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: worker.garden.sapcloud.io/group
                operator: In
                values:
                  - scalehist
  terminationGracePeriodSeconds: 30
  serviceAccountName: "default"
  containers:
    - name: app
      image: ${DOCKERHUB_USER}/scaling-history-app:latest
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: 500Mi
        limits:
          memory: 1Gi
      env:
        - name: MODE
          value: in-utility-cluster
        - name: REPORT_DIR
          value: /data/reports
        - name: DB_DIR
          value: /data/db
        - name: DOCKERHUB_USER
          value: ${DOCKERHUB_USER}
      volumeMounts:
        - mountPath: /data
          name: data-dir
        - mountPath: /cfg
          name: recorder-config
        - mountPath: /app/secrets/gardens
          name: landscapes
  volumes:
    - name: data-dir
      persistentVolumeClaim:
        claimName: scaling-history-data
    - name: recorder-config
      projected:
        sources:
        - configMap:
            name: scaling-history-recorder-config
    - name: landscapes
      secret:
        defaultMode: 420
        secretName: landscapes