apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: "scaling-history-recorder"
  name: recorder-pvc
  namespace: shoot--hc-canary--prod-hna0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: default

---

#apiVersion: v1
#automountServiceAccountToken: false
#kind: ServiceAccount
#metadata:
#  name: scaling-history-recorder-sa
#  namespace: shoot--hc-canary--prod-hna0

---

apiVersion: v1
kind: Pod
metadata:
  name: scaling-history-recorder
  namespace: shoot--hc-canary--prod-hna0 #TODO
  labels:
    app.kubernetes.io/name: "scaling-history-recorder"
    networking.gardener.cloud/to-dns: allowed
    networking.gardener.cloud/to-runtime-apiserver: allowed
    networking.resources.gardener.cloud/to-kube-apiserver-tcp-443: allowed
    role: cluster-autoscaler
    app: kubernetes
    gardener.cloud/role: controlplane
spec:
  terminationGracePeriodSeconds: 30
  serviceAccount: "scaling-history-recorder-sa"
  containers:
    - name: recorder
      image: aaronfernandes/recorder:latest
      resources:
        limits:
          memory: 4Gi
      env:
        - name: CONTROL_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: MODE
          value: in-control-plane
        - name: DB_DIR
          value: /var/data/db-dir
      volumeMounts:
        - mountPath: /var/run/secrets/gardener.cloud/shoot/generic-kubeconfig
          name: kubeconfig
          readOnly: true
        - mountPath: /var/data/db-dir
          name: db-dir
  volumes:
    - name: db-dir
      persistentVolumeClaim:
        claimName: recorder-pvc
    - name: kubeconfig
      projected:
        defaultMode: 420
        sources:
          - secret:
              items:
                - key: kubeconfig
                  path: kubeconfig
              name: generic-token-kubeconfig-dec7d246
              optional: false
          - secret:
              items:
                - key: token
                  path: token
              name: shoot-access-cluster-autoscaler
              optional: false

