apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: "scaling-history-recorder"
  name: scaling-history-data
  namespace: mcm-ca-team
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: default
---



---
apiVersion: v1
kind: Pod
metadata:
  name: scaling-history-recorder
  namespace: mcm-ca-team
  labels:
    app.kubernetes.io/name: "scaling-history-recorder"
    networking.gardener.cloud/to-dns: allowed
    networking.gardener.cloud/to-runtime-apiserver: allowed
    networking.resources.gardener.cloud/to-kube-apiserver-tcp-443: allowed
    role: cluster-autoscaler
    app: kubernetes
    gardener.cloud/role: controlplane
spec:
  terminationGracePeriodSeconds: 30
  #serviceAccountName: "robot"
  serviceAccountName: "default"
  restartPolicy: Always
  tolerations:
    - key: dedicated
      value: scaling-history
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: worker.garden.sapcloud.io/group
                operator: In
                values:
                  - scalehist
  containers:
    - name: recorder
      image: ${DOCKERHUB_USER}/scaling-history-recorder:latest
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: 12Gi
        limits:
          memory: 18Gi
      env:
        - name: MODE
          value: in-utility-cluster
        - name: DB_DIR
          value: /data/db
        - name: REPORT_DIR
          value: /data/reports
      volumeMounts:
        - mountPath: /data
          name: data-dir
        - mountPath: /app/secrets/gardens
          name: gardens
        - mountPath: /cfg
          name: recorder-config
  volumes:
    - name: data-dir
      persistentVolumeClaim:
        claimName: scaling-history-data
    - name: gardens
      secret:
        defaultMode: 420
        secretName: gardens
    - name: recorder-config
      projected:
        sources:
        - configMap:
            name: scaling-history-recorder-config