apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: "scaling-history-recorder"
  name: recorder-pvc
  namespace: robot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: default

---



---

apiVersion: v1
kind: Pod
metadata:
  name: scaling-history-recorder
  namespace: robot #TODO
  labels:
    app.kubernetes.io/name: "scaling-history-recorder"
    networking.gardener.cloud/to-dns: allowed
    networking.gardener.cloud/to-runtime-apiserver: allowed
    networking.resources.gardener.cloud/to-kube-apiserver-tcp-443: allowed
    role: cluster-autoscaler
    app: kubernetes
    gardener.cloud/role: controlplane
spec:
  terminationGracePeriodSeconds: 30
  serviceAccount: "robot"
  containers:
    - name: recorder
      image: aaronfernandes/recorder:latest
      resources:
        limits:
          memory: 4Gi
      env:
        - name: SHOOT_NAMESPACE
          value: shoot--hc-canary--prod-hna0 #TODO
        - name: MODE
          value: in-utility-cluster
        - name: DB_DIR
          value: /var/data/db-dir
      volumeMounts:
#        - mountPath: /var/run/secrets/gardener.cloud/shoot/generic-kubeconfig
#          name: kubeconfig
#          readOnly: true
        - mountPath: /var/data/db-dir
          name: db-dir
        - mountPath: /app/secrets/gardens
          name: robot-gardens
        - mountPath: /cfg
          name: recorder-config
  volumes:
    - name: db-dir
      persistentVolumeClaim:
        claimName: recorder-pvc
#    - name: kubeconfig
#      projected:
#        defaultMode: 420
#        sources:
#          - secret:
#              items:
#                - key: kubeconfig
#                  path: kubeconfig
#              name: generic-token-kubeconfig-dec7d246
#              optional: false
#          - secret:
#              items:
#                - key: token
#                  path: token
#              name: shoot-access-cluster-autoscaler
#              optional: false
    - name: robot-gardens
      secret:
        defaultMode: 420
        secretName: robot-gardens
    - name: recorder-config
      projected:
        sources:
        - configMap:
            name: scaling-history-recorder-config

