apiVersion: v1
kind: Pod
metadata:
  name: ${POD_NAME}
  namespace: mcm-ca-team
  annotations:
    nonce: "${NONCE}"
  labels:
    app.kubernetes.io/name: "scaling-history-replayer"
    networking.gardener.cloud/to-dns: allowed
    networking.gardener.cloud/to-runtime-apiserver: allowed
    networking.resources.gardener.cloud/to-kube-apiserver-tcp-443: allowed
    role: cluster-autoscaler
    app: kubernetes
    gardener.cloud/role: controlplane
spec:
  tolerations:
    - key: dedicated
      value: scaling-history
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: worker.garden.sapcloud.io/group
                operator: In
                values:
                  - scalehist
  restartPolicy: Never
  containers:
    - name: replayer
      image: ${DOCKERHUB_USER}/scaling-history-replayer:latest
      env:
        - name: INPUT_DATA_PATH
          value: "${POD_DATA_PATH}"
        - name: REPORT_DIR
          value: "/reports"
        - name: NO_AUTO_LAUNCH
          value: "${NO_AUTO_LAUNCH}"
#      volumeMounts:
#         - mountPath: /reports
#           name: reports-dir
      resources:
        requests:
          memory: ${MEMORY}
#  volumes:
#    - name: reports-dir
#      persistentVolumeClaim:
#        claimName: scaling-history-reports