apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: "scaling-history-replayer"
  name: shr-reports
  namespace: robot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: default
---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: scaling-history-replayer-config
#  namespace: robot
#data:
#  INPUT_DATA_PATH: "${INPUT_DATA_PATH}"