apiVersion: v1
kind: Pod
metadata:
  generateName: scaling-history-replayer-
  namespace: mcm-ca-team
  annotations:
    nonce: "${NONCE}"
  labels:
    app.kubernetes.io/name: "scaling-history-replayer"
    networking.gardener.cloud/to-dns: allowed
    networking.gardener.cloud/to-runtime-apiserver: allowed
    networking.resources.gardener.cloud/to-kube-apiserver-tcp-443: allowed
    role: cluster-autoscaler
    app: kubernetes
    gardener.cloud/role: controlplane
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key:  "app.kubernetes.io/name"
                operator: In
                values:
                    - "scaling-history-recorder"
          topologyKey: "kubernetes.io/hostname"
  restartPolicy: Never
  containers:
    - name: replayer
      image: ${DOCKERHUB_USER}/scaling-history-replayer:latest
##          ports:
##            - containerPort: 8080
#          resources:
#            limits:
#              memory: 3Gi
      #envFrom:
      #  - configMapRef:
      #      name: scaling-history-replayer-config
      env:
        - name: INPUT_DATA_PATH
          value: ${INPUT_DATA_PATH}
        - name: REPORT_DIR
          value: /data/reports
      volumeMounts:
         - mountPath: /data
           name: data-dir
  volumes:
    - name: data-dir
      persistentVolumeClaim:
        claimName: scaling-history-data