apiVersion: apps/v1
kind: Deployment
metadata:
  name: scenario4b
  labels:
    app: demob
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demob
  template:
    metadata:
      labels:
        app: demob
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: demob
      containers:
      - name: pause
        image: registry.k8s.io/pause:3.5
        resources:
          requests:
            cpu: 100m
            memory: 12Gi